steps:
- name: gcr.io/kaniko-project/executor:latest
  id: 'Build1'
  args: ['--destination=$_IMAGE1_NAME:$COMMIT_SHA','--destination=$_IMAGE1_NAME:latest','--cache=true', '--dockerfile=$_IMAGE1_DOCKERFILE_PATH']
  timeout: 500s
- name: "gcr.io/cloud-builders/gke-deploy"
  id: 'Deploy'
  args:
  - run
  - --filename=$_K8S_YAML_PATH
  - --image=$_IMAGE1_NAME:$COMMIT_SHA
  - --location=$_K8S_LOCATION
  - --cluster=$_K8S_CLUSTER
  timeout: 500s
substitutions:
  _IMAGE1_NAME: gcr.io/fuse-ai/test-app-kaniko
  _IMAGE1_DOCKERFILE_PATH: Dockerfile
  _K8S_APP_NAME: flask-app
  _K8S_NAMESPACE: default
  _K8S_YAML_PATH: deployment.yaml
  _K8S_LOCATION: us-central1-c
  _K8S_CLUSTER: cluster-1
options:
  substitution_option: 'ALLOW_LOOSE'
timeout: 1000s
tags: [$COMMIT_SHA,$_K8S_APP_NAME]
#logsBucket: 'gs://cloudbuild-logs'